### ISSUE TITLE
cfx no longer supported for Firefox 44+

### ISSUE THREAD

**Issue by teddyzeenny** [rpl/grunt-mozilla-addon-sdk#26]
It seems addons built with cfx are no longer accepted. Should we move this to jpm?

**Comment by rpl** [comment]
@teddyzeenny As jpm can be used as an npm dependency instead of retrieving it from a addon-sdk release tarball as required for cfx, sometimes ago I've prepared [grunt-jpm](https://npmjs.com/package/grunt-jpm) as a lightweight alternative to integrate jpm xpi building into a gruntfile.

I just created emberjs/ember-inspector#519 to integrate "jpm run" and "jpm xpi" into the the Ember Inspector building process (which shows how to port a gruntfile from grunt-mozilla-addon-sdk to grunt-jpm).
